In [1]:
import numpy as np 
from scipy.spatial import distance

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
 
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly import graph_objs as go
init_notebook_mode(connected=True)
import numpy as np

import random

from IPython.display import display, Math

from bokeh.io import show, output_notebook, reset_output
from bokeh.plotting import figure, show
from scipy.stats import norm 
from bokeh import plotting as pl
from bokeh.models import HoverTool, Arrow, OpenHead, NormalHead, VeeHead, Span, ColumnDataSource, PointDrawTool, TableColumn,  DataTable

reset_output()
output_notebook()

Loading BokehJS ...

In [ ]:
''' In order for us to get into the details of linear algebra first we will have to learn to speak its language.
Hence in this in this section we are going to focus on some core concepts in linear algebra. These will be -

1) Scalars and Vectors 
2) Matrices 
3) Algebra of Matrices 
4) Inverse and transpose of a Matrix 
5) Eigenvectors and Eigenvalues 

In this notebook we are going to talk about-
  1) Scalars and vectors  definitions  <br>
  3) Magnitude of a vector  <br>
  4) Unit vector <br>
  5) Vector arithmetic <br>
So lets get started!'''

## Scalars and Vectors

In [ ]:
""" One of the fundamental quantities we will work with is a scalar. A scalar, simply put is any real number. For example, 
if you measure your weight, you are representing 
your weight with a real number. This is called a scalar. The height of a building, is a scalar. Scalar are a single value, 
they can be positive or negative. For example -45 celcius is a scalar quantity as well.

A vector is an ordered collection of elements. We usually write a vector  𝐀  as -

𝐀  = [ 𝑎1,𝑎2 ]
where  𝑎1  and  𝑎2  are scalars. We will be using square brackets to represent vectors and matrices which w

They are also called components or elements of the vector  𝐀 

The order of (  𝑎1,𝑎2 ) matters. This is because if have another vector  𝐁  = [ 𝑎2,𝑎1 ], then

𝐀   ≠   𝐁 
For  𝐀  to be equal to  𝐁  we need the order of  𝑎1  and  𝑎2  to be the same both vectors.

The definition that we have presented seems a bit too theoretical. So lets try to get an intuitive feel for what all of 
the above means. For example, we mentioned earlier that weight was a scalar. With weight, you really just need that single 
number to describe what your are measuring on the scale. If that is the case why do you need a vector?

Well try and describe to someone a position of a building on the map.

Question: How many numbers do you need to describe the location of building on a paper map

Answer: Lay out a paper map. Try to find any street or building on it. You will find you will need two numbers on the map. 
The latitude and the longitude. So the position on the map can be written down as -

Position on map = [latitude, longitude]

this is a vector quantity! How? Well, the position has two components. Also, it is ordered, meaning we cannot swap the 
latitude and longitude values, if we do then we will get a completely different location.


There are many quantities that can be considered as vectors- Position on a map, velocity of an object, airflow, force applied
to a object.

We will talk a little bit about position as a vector because it is the easiest way to highlight some of the ideas the basic 
ideas behind vectors

Usually positions of objects are represented on a something called a cartesian grid. In python we can easily do this. 
We going to plot the position of point (x,y) on a grid."""

In [2]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


fig = pl.figure(x_range =[0,10],
                    y_range =[0,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis", 
                   title  = "Red point is point P "
                   )
    
    
source = ColumnDataSource({
    'x': [4], 'y': [5], 'color': ['red']
})
    
fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end="x",
                       y_end="y", 
                    source = source))
renderer = fig.scatter("x","y",size = 12, color= "color", source  =source)
# fig.text(x=source.data["x"][0] , y=source.data["y"][0]+0.2, text=["P"])
draw_tool = PointDrawTool(renderers=[renderer], empty_value='black')
fig.add_tools(draw_tool)
fig.toolbar.active_tap = draw_tool

hover = fig.select(dict(type=HoverTool))
hover.tooltips = [("xvalue", "$x"), ("yvalue", "$y")]
show(fig)

In [ ]:
""" In the plot above we have a position of a point on the grid. For example, lets say that the point P is you on a football 
field 
and 1 unit on the grid is 1 meter. So to get to where you are, starting from the football field we are going to have to walk
4 meter right and 5 meter up. We can say that your position which is a vector has direction which is given by the components 
4 units right and 5 units up.

Magnitude of a vector
Vectors have another proper called magnitude. The magnitude (also known as the absolute value) is the distance between two 
vectors. In simple terms magnitude the length of the black line in the plot.

Magnitude of the vector is defined as -

| 𝐀 | =  (𝑎12+𝑎22)⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯√ 

In python we can represent vectors as either lists or numpy arrays. To calculate magnitude easily, we will represent 
it as a numpy array."""

In [3]:
# vector in numpy

A =np.array([5,4])
# magnitude of a vector using numpy linear algebra package
magnitude = np.linalg.norm(A,1)
print("magnitude of point P is {}".format(magnitude))

magnitude of point P is 9.0


In [ ]:
The magnitude of point any P represents the distance between the point (0,0) which is called the origin and the point P.

### Unit vector


In [ ]:
Unit vector
When we talk about vectors there is also also a sense of direction that we can capture. Take point P for example, 
we calculated its magnitude but would two vectors  𝐏1  and  𝐏2  be the same if they have the same magnitude, not really 
because on the x-y grid you have them point in different directions. Take a look at the plot below

In [4]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


fig = pl.figure(x_range =[0,10],
                    y_range =[0,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis", 
                   title  = "Two vectors with the same magnitude "
                   )
    
    
source = ColumnDataSource({
    'x': [4, 5], 'y': [5, 4], 'color': ['red', 'green']
})
fig.scatter("x","y",size = 12, color= "color", source  =source)
   
fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end="x",
                       y_end="y", 
                    source = source))

show(fig)

In [ ]:
''' This is why need to quantify a sense of direction for a vector. This is provided by the unit vector. The unit vector is a vector whose magnitude is always 1 but x and y components keeps changing on the basis of direction. So for example -

𝑥̂ =[1,0]𝑦̂ =[0,1]
the vector  𝑥̂   represents the unit vector in the x direction on a x-y grid. Similarly, the vector  𝑦̂   represents a unit vector in the y direction. Below is the plot of a unit vector and its components.'''

In [5]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


# go by vector orientation 

def vec_plot(vec_1_ort):
    vec_1 = [0,1]
 
    vec_1_x = vec_1[0]*np.cos(vec_1_ort)  + vec_1[1]*np.sin(vec_1_ort) 
    vec_1_y = -vec_1[0]*np.sin(vec_1_ort) +vec_1[1]*np.cos(vec_1_ort)
    
    magnitude = np.linalg.norm([vec_1_x, vec_1_y])
    
    fig = pl.figure(x_range =[0,3],
                    y_range =[0,3], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis"
                   )
    
    
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=vec_1_x,
                       y_end=vec_1_y))
    


    
    fig.circle(vec_1_x,vec_1_y,size = 12, color= "red")
    fig.text(x= 1, y =2.5, text =["x_component \n" + " "+str(np.round(vec_1_x, 2))])
    fig.text(x= 2.0, y =2.5, text =["y_component \n" + " " +str(np.round(vec_1_y, 2))])
    fig.text(x = 1.5, y= 1.75, text = [ "Magnitude \n" + " " +str(np.round(magnitude, 2))] )
    hover = fig.select(dict(type=HoverTool))    
    hover.tooltips = [("xvalue", "$x"), ("yvalue", "$y")]
    show(fig)
    return 

interact(vec_plot, 
                   vec_1_ort = widgets.FloatSlider(value = 0, min= 0, max =1.57, step =0.01 )
        
                 
        
        )

interactive(children=(FloatSlider(value=0.0, description='vec_1_ort', max=1.57, step=0.01), Output()), _dom_cl…

<function __main__.vec_plot(vec_1_ort)>

In [ ]:
''' This is why when we talk about defining a vector we talk about an object that has both magnitude, 
which represents the length of a vector and a direction, which tells us what direction the vector is point to. 
Hence, for us to say that two vectors are equal, they must have the same magnitude and direction as well.

Vector arithmetic
In order to talk about vector arithmetic. Lets take a simple example

Suppose you are standing at point P =  [4,5] . Now suppose you have a friend who joins you on the football field and 
he is standing at the point Q. So to get to him someone will have to walk 2 units up and 8 units, right hence Q=(8,2). 
So how would you, who is at point P get to where your friend is?

well that would be

R = Q-P = [8, 2] - [4,5] = [8-4,2-5]= [4,-3]

so to get to Q, you need to walk 4 right and 3 units down (hence the negative sign). Take a look at the plot below'''

In [6]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        

def vec_plot(x,y):
    fig = pl.figure(x_range =[0,10],
                    y_range =[0,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis"
                   )
    
    
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=x,
                       y_end=y))
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=8,
                       y_end=2))
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=x,
                       y_start=y,
                       x_end=8,
                       y_end=2))
    

    p = np.array([x,y])
    q = np.array([8,2])
    
    r_dist =  np.linalg.norm(p-q)
    fig.circle(x,y,size = 12, color= "red")
    fig.circle(x = 8,y = 2,size = 12, color= "green")
    
    fig.text(x=x, y=y+0.2, text=["P"])
    fig.text(x=8, y=2+0.2, text=["Q"])
    fig.text(x=(8-x)/2+ x, y=-(2-y)/2+(y/2), text=["R"])
    
    hover = fig.select(dict(type=HoverTool))    
    hover.tooltips = [("xvalue", "$x"), ("yvalue", "$y")]
    show(fig)
    print("distance between points Q and P is {} units".format(np.round(np.linalg.norm(p-q),2)))
    return 

interact(vec_plot, 
                   x = widgets.FloatSlider(value = 4, min= 1, max =9, step =0.01 ),
        
                     y = widgets.FloatSlider(value = 5, min= 1, max =9, step =0.01 ), 
        
        )

interactive(children=(FloatSlider(value=4.0, description='x', max=9.0, min=1.0, step=0.01), FloatSlider(value=…

<function __main__.vec_plot(x, y)>

In [ ]:
Now that we have a general idea of what a vector is lets talk about the two configuration of vectors- Row vectors 
and column vectors.

A row vector is written as A =  [𝑎,𝑏]  and a column vector is written as B =  [𝑐𝑑] . Example of row vectors would be 
A =  [2,4,52] , B =  [7,1,5] . The corresponding column vectors would be.

A =  2452 
B =  715 
We can convert a row vector to a column vector using the transpose operation. The transpose operation is more generally
defined for a matrix but in case of a vector it lets us write a row vector as a column vector. Take for example, 
the row vector A =  [2,4,52] , the corresponding column vector would be

A 𝑇  =  2452 
We can also write this as  [2,4,52]𝑇 
All of this will be relevant especially when we start talking about vector multiplication

From the previous plot, in acquiring R what we have shown is that we can subtract vectors. There are other operations
that we can do with vectors as well-

𝐀𝐝𝐝𝐢𝐭𝐢𝐨𝐧 𝐨𝐟 𝐕𝐞𝐜𝐭𝐨𝐫𝐬− 

𝐀+𝐁=[𝑎1+𝑏1,𝑎2+𝑏2] 

 𝐒𝐮𝐛𝐭𝐫𝐚𝐜𝐭𝐢𝐨𝐧 𝐨𝐟 𝐕𝐞𝐜𝐭𝐨𝐫𝐬− 

𝐀−𝐁=[𝑎1−𝑏1,𝑎2−𝑏2] 

For both addition and subtraction, you can add or subtract only row vectors to row vectors and column vectors to column vectors.

In the next notebook we will spend some time talking about vector multiplication.

In [ ]:
3x-9y = -42
2x +4y = 2

In [8]:
A = np.array([[3,-9],[2,4]])
print(A)

[[ 3 -9]
 [ 2  4]]


In [11]:
B = np.array([-42,2])


In [12]:
z = np.linalg.solve(A,B)
print(z)

[-5.  3.]


In [ ]:
x-2y-z = 6
2x+2y = z+1
2z-1 = y+x

In [13]:
M = np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
N = np.array([6,1,1])

z=np.linalg.solve(M,N)
print(z)

[ 3. -2.  1.]


## Multiplying two vectors

In [ ]:
Unlike adding vectors, multiplying vectors is a bit more different. There are three types of vector multiplications you can 
do-

# Dot product (yields a scalar)
# Cross product (yields a vector )
# Vector direct product (yields a tensor)

In this notebook, we are going to talk about how to do each one of them and discuss examples.

Dot product
In a dot product, the product of two vectors yields a scalar-

[a1,a2]∙[b1b2]=(a1∗b1)+(a2∗b2) 
Question: So looking at the above equation, If you have two vectors  [1,2]  and  [3,4]T  what do you think will the dot 
    product ? Note  [3,4]T  is a column vector

Answer: The dot product would be - [1,2]∙[34]=(1∗3)+(2∗4)=3+8=11

### DOT PRODUCT

In [ ]:
It is important to note that the order of operation here must be always the same. The row vector must be to the left and 
the column vector must be to the right.

For dot product we write in general -

a∙b=[a1,a2]∙[b1b2]=(a1∗b1)+(a2∗b2) 
We can do dot products in python as well. To do a dot product in python we can use numpy.

In [14]:
dot_product = np.dot([1,2], [3,4])
print("dot product value for is {} " .format(dot_product))

reverse_dot_product = np.dot([3,4], [1,2])
print("We swap the vectors fromt their positions, then the dot product is {}" .format(reverse_dot_product))


dot product value for is 11 
We swap the vectors fromt their positions, then the dot product is 11


In [ ]:
In the above code block we showed that -

𝐚   ∙   𝐛  =  𝐛   ∙   𝐚 
this is the property of being commutative. We can swap the position of both vectors  𝐚  and  𝐛  and still get the same result.

The dot product also has a geometric definition. which is given by -

𝐚∙𝐛=|𝐚||𝐛|cos𝜃
 
where  |𝐚|  is the absolute value of the vector.

In the below figure you can see how the value of the dot product changes as you vary the vectors

The angle  𝜃  is the angle between the vectors.



In [15]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


# go by vector orientation 

def vec_plot(vec_1_ort,vec_2_ort):
    vec_1 = [0,6]
    vec_2 =[8,0]

    vec_2_ort = - vec_2_ort
    vec_1_x = vec_1[0]*np.cos(vec_1_ort)  + vec_1[1]*np.sin(vec_1_ort) 
    vec_1_y = -vec_1[0]*np.sin(vec_1_ort) +vec_1[1]*np.cos(vec_1_ort)
    
    
    vec_2_x = vec_2[0]*np.cos(vec_2_ort)  + vec_2[1]*np.sin(vec_2_ort) 
    vec_2_y = -vec_2[0]*np.sin(vec_2_ort) +vec_2[1]*np.cos(vec_2_ort)
    
    denom = (np.linalg.norm([vec_1_x, vec_1_y]) *np.linalg.norm([vec_2_x, vec_2_y]))
    numer = np.dot([vec_1_x,vec_1_y ],[vec_2_x,vec_2_y ] )
    angle_between  = np.rad2deg( np.arccos(numer/ denom))
    dot_product_value = numer
    
    
    fig = pl.figure(x_range =[0,10],
                    y_range =[0,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis"
                   )
    
    
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=vec_1_x,
                       y_end=vec_1_y))
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=vec_2_x,
                       y_end=vec_2_y))
    

    
    fig.circle(vec_1_x,vec_1_y,size = 12, color= "red")
    fig.circle(vec_2_x,vec_2_y,size = 12, color= "green")
    
    fig.text(x=6.0, y=8.0, text=["Angle between  \n =  " + str(np.round(angle_between,2)) ])
    fig.text(x=2.0, y=8.0, text=["Dot product \n value =" + str(np.round(dot_product_value,2))])
#     fig.text(x=(8-x)/2+ x, y=-(2-y)/2+(y/2), text=["R"])
    
    hover = fig.select(dict(type=HoverTool))    
    hover.tooltips = [("xvalue", "$x"), ("yvalue", "$y")]
    show(fig)
    return 

interact(vec_plot, 
                   vec_1_ort = widgets.FloatSlider(value = 0, min= 0, max =1.57, step =0.01 ),
        
                     vec_2_ort = widgets.FloatSlider(value = 0, min= 0, max =1.57, step =0.01 ), 
        
        )

interactive(children=(FloatSlider(value=0.0, description='vec_1_ort', max=1.57, step=0.01), FloatSlider(value=…

<function __main__.vec_plot(vec_1_ort, vec_2_ort)>

In [ ]:
As you can see when the angle between the vectors is 0 then the dot product a maximum, if the angle between the vector is 90 i.e they are perpendicular of the dot product is 0.

The dot product yields a scalar value next we are going to see a product that yields a vector value.

Next we have the cross product-

### CROSS PRODUCT

In [ ]:
Unlike the dot product, the cross product yields us a vector product. Meaning the product of two vectors is a vector, we are not going into details of how it is calculated. Usually, we work with vectors in 3 or more dimensions for the cross product. The general definition of the cross product is given below where the vectors  𝐚  and  𝐛  have 3 components.

𝐚×𝐛=(𝑎1𝑥̂ +𝑎2𝑦̂ +𝑎3𝑧̂ )×(𝑏1𝑥̂ +𝑏2𝑦̂ +𝑏3𝑧̂ )
=𝑎1𝑏1(𝑥̂ ×𝑥̂ )+𝑎1𝑏2(𝑥̂ ×𝑦̂ )+𝑎1𝑏3(𝑥̂ ×𝑧̂ )
+𝑎2𝑏1(𝑦̂ ×𝑥̂ )+𝑎2𝑏2(𝑦̂ ×𝑦̂ )+𝑎2𝑏3(𝑦̂ ×𝑧̂ )
+𝑎3𝑏1(𝑧̂ ×𝑥̂ )+𝑎3𝑏2(𝑧̂ ×𝑦̂ )+𝑎3𝑏3(𝑧̂ ×𝑧̂ )

where
𝑥̂ ×𝑦̂ =𝑧̂ 𝑥̂ ×𝑧̂ =𝑦̂ 𝑦̂ ×𝑧̂ =𝑥̂ 
the above follows from commutivity rules and the anti commutivity rules are -

𝑦̂ ×𝑥̂ =−𝑧̂ 𝑧̂ ×𝑦̂ =−𝑦̂ 𝑧̂ ×𝑦̂ =−𝑥̂ 
the geometric interpretation of the cross product is given by the relationship

𝐚×𝐛=|𝐚||𝐛|sin𝜃
 
where  𝜃  is the angle between two vectors

As you can see, calculating a cross product can get rather messy by hand. 
Thankfully python provides us a simple way of doing this. Which is using numpy.

In [16]:
vector_1 = [2, 3, 5]
vector_2 = [5,-9, 8]

cross_product_value = np.cross(vector_1, vector_2)

print("The new vector from the cross product will be vector_3  = {}" .format(cross_product_value))




The new vector from the cross product will be vector_3  = [ 69   9 -33]


## Introduction to Matrices¶


### What is a Matrix?¶


In [ ]:
A matrix is a set of numbers, symbols and expressions which are arranged in a rectangular fashion using rows and columns.

Consider a matrix  A , which consists of 'm' rows and 'n' columns, at the intersection of each row and column, there would be an element of the matrix, which may be a number, symbol or expression. Therefore, in a matrix with 'm' rows and 'n' columns, there would be 'm*n' elements. The dimensions of the matrix would be m x n (Read as: m cross n), i.e. 'm' rows and 'n' columns.

A matrix is generally denoted by a rectangular array of numbers enclosed within square brackets.

A=⎡⎣⎢147258369⎤⎦⎥ 
A  here is a 3 X 3 matrix and it has 9 elements (also widely referred to as 'entries').

Also, entries in a matrix can be more than just numbers - like symbols and expressions.

B=⎡⎣⎢αγλβδπ⎤⎦⎥ 
or

C=[3x+4y+1−2x+3y32x2−6y25x2−23y+18]

### Types of Matrices - 1

In [ ]:
|Depending mostly upon the nature and positioning of entries, various types of matrices are possible. We will discuss and define a few common and important types of matrices here. Below described matrices are some of the basic types of matrices. We will look at slightly more advanced matrix types in a later section, after learning about matrix operations. For a larger list of various types of matrices refer to (Link: https://en.wikipedia.org/wiki/List_of_matrices)

# Row Matrix
A matrix which consists of one and only one row (there can be any number of columns) is called a 'row matrix'.

For e.g.

A=[123]
or
B=[αβγδ]

# Column Matrix
A matrix which consists of entries arranged in one and only one column, is called a 'column matrix'.

For e.g.

A=⎡⎣⎢⎢⎢abcd⎤⎦⎥⎥⎥
or
B=⎡⎣⎢122436⎤⎦⎥

# Square Matrix
By definition, matrix is a rectangular array of entries. A square is nothing but a special rectangle where its length equals its breadth. Similarly, a square matrix is one where it has equal number of rows and columns.

For e.g.

A=[1324]

here A is a 2 X 2 square matrix. i.e. 2 rows and 2 columns

or

B=⎡⎣⎢αδλβϕπγωμ⎤⎦⎥

B is a 3 X 3 square matrix.

Note: A square matrix with n x n dimensions will have n2 elements.

Before we discuss further about other types of matrices, we would like to introduce the concept of diagonal elements in a square matrix.

Entries/Elements in a matrix: As we know, by definition the number of columns is equal to the number of columns. Say i is a variable representing the number of row and j be representing the number of column, then the element xij is nothing but the element present in the intersection of the ith row and jth column. For example:

Let A be a 3 x 3 matrix with the following entries

A=⎡⎣⎢147258369⎤⎦⎥
If a is the symbol of an entry in matrix A then, a31 by convention is the element in the 3rd row and 1st column. The row and column numbers may also be separated by a comma or space.

In the above example,
a31=7
a12=2
a22=5 and so on.

#### Diagonals of a matrix¶


In [ ]:
Within a square matrix of dimensions n x n, the elements which can be denoted by  aij  where  i  is equal to  j  are called 
diagonal elements and they together constitute the diagonal of the square matrix. So all elements of the form  aii  where  
i  belongs to [1,2,3...n] consitute the diagonal of the matrix.

In the above example the diagonal of matrix  A  constitutes the elements { a11,a22,a33 }, i.e., {1,5,9} are the diagonal 
elements in the above example. This diagonal is called the primary diagonal or leading diagonal of the matrix. There is 
also a trailing diagonal or antidiagonal of a square matrix. The below image shows the leading and trailing diagonals in a
3x3 square matrix.


Diagonal Matrix
The diagonal matrix is a square matrix in which the diagonal elements have some quantitative value and all other elements 
are zeroes.

For e.g.

D=⎡⎣⎢300060009⎤⎦⎥ 

D  is a 3 X 3 diagonal matrix.

There are further two important types of Diagonal Matrices:

Unit Matrix or Identity Matrix
This is a diagonal matrix where all the elements of the diagonal are 1.

For e.g.

I=⎡⎣⎢100010001⎤⎦⎥ 

I  is a 3 X 3 unit matrix.

The unit matrix is also called as 'Identity Matrix'. This is because in matrix multiplication (which we will study in 
the next section) any matrix  S  of dimensions m x n when multiplied by a unit matrix of dimensions n x n, results in itself. 
That is, if  S  is the matrix in question and  I  is a compatible unit matrix, then -

S∗I=S 
Scalar Matrix
This is a diagonal matrix where all the elements of the diagonal are of the same value. It is called a scalar matrix 
because it can be written as the product of a scalar and an identity matrix.

For e.g.

S=[700
    070
    007] 

S  is a 3 X 3 scalar matrix.

Zero or Null Matrix
A matrix where all entries are zeroes is called a zero matrix or a null matrix.

For e.g.

Z1=[000
    000] 

Z2=[00
    00] 

Z3=⎡⎣⎢000
     000
     000⎤⎦⎥ 

Z1,Z2,Z3  are all zero matrices.

## Implementation of Matrices in Python¶


In [ ]:
# There are two ways of creating matrices in Python.

# 1. Declare a list of lists. The number of levels of nesting and the length of each nested list determine the dimensions 
# of the matrix.
# 2. Initialize a numpy nd-array (n-dimensional array).
# For e.g.,

# List of lists implementation
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

# Nd-array implementation
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
here are also some dedicated functions in numpy to create Null matrices, Identity matrices and matrices where all entries are 
1s.

For e.g.,

import numpy as np

# A 3x3 Null matrix
z = np.zeros((3,3))
z

# Output
>>> array([[0., 0., 0.],
>>>        [0., 0., 0.],
>>>        [0., 0., 0.]])

# A 3x3 Identity matrix
i = np.eye(3)
i

# Output
>>> array([[1., 0., 0.],
>>>        [0., 1., 0.],
>>>        [0., 0., 1.]])

# A 3x3 matrix with all entries as 1s
a = np.ones((3,3))
a

# Output
>>> array([[1., 1., 1.],
>>>        [1., 1., 1.],
>>>        [1., 1., 1.]])
'''
Question: From the above examples we can observe that 'zeros' and 'ones' function takes a tuple as an argument which specifies 
    the dimensions of the matrix to be created. However, 'eye' function takes only an integer as an argument. Do you know why?
Answer: A Null matrix is not necessarily a square matrix and can have any dimensions as long as all entries are zeroes. Same 
    goes for the matrix which has 1s as entries, it can have any dimensions. However, an identity matrix is always a square 
    matrix hence one integer value 'n' is enough to create a nxn identity matrix.'''

#### Exercise

In [ ]:

# Initialize the following matrices

# A matrix with entries of integers from 1 through 12, with the dimensions 3x4.
# Define a scalar_mat() function which takes in 2 elements - 'n' which determines the nxn dimensions of the scalar matrix and 
# 'a' the entry which fills all positions in the primary diagonal. Use this function to create a 4x4 scalar matrix with diagonal 
# elements as 256.
A 5x5 identity matrix.

In [17]:
import numpy as np

a = np.reshape(np.arange(1,13),(3,4))

def scalar_mat(n,a):
    scalar_matrix = np.zeros((n,n))
    for i in range(0,n):
        scalar_matrix[i][i]=a
    return scalar_matrix

b = scalar_mat(4,256)

c = np.eye(5)

a,b,c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[256.,   0.,   0.,   0.],
        [  0., 256.,   0.,   0.],
        [  0.,   0., 256.,   0.],
        [  0.,   0.,   0., 256.]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

## Basic Matrix Operations

Before we learn further about various matrices and their properties, we need to learn basic matrix operations. We will learn about basic arithmetic operations of matrices such as addition, subtraction, multiplication etc. and then we will also learn about special operations specific to matrices.

### Addition and Subtraction

Addition can be performed between two scalars (which is the addition of two numbers), a scalar and a matrix or between two matrices.
* Scalar addition: General addition of two numbers.
```python
a = 5
b = 4
c = a+b
```
* Scalar-Matrix addition: Addition of a scalar value to each value within the given Matrix
<img src="../../../images/mat_scad.PNG" style="width:60vw">
<br>
* Matrix addition: Addition of two matrices. Two matrices can be added, only if they have the same dimensions. This is because matrix addition is nothing but a collection of scalar additions - each entry is added to the entry in the second matrix which is at the same position. i.e., If entries in matrix $A$ are denoted by $a_{ij}$ where $i$ is the row number and $j$ is the column number of the entry, denoting the position of the entry in the matrix, and if in matrix $B$ entries are denoted by $b_{ij}$ then for a given combination of $i$ and $j$, $a_{ij}+b{ij}$ would be the entry in the resulting additive matrix at position $i,j$. Same rules hold true for subtraction. For these operations, matrices can be treated as variables and '+' and '-' operators can be used to perform addition and subtraction.
 
<b>Addition</b>

<img src="../../../images/mat_add.PNG" style="width:60vw">

<br>

<b>Subtraction</b>

<img src="../../../images/mat_sub.PNG" style="width:60vw">
<br>

### Matrix Multiplication and Division(!)

Two matrices can be multiplied with each other if the number of columns of the first matrix is equal to the number of rows of the second matrix. The product of two matrices will be another matrix with dimensions as -
* number of rows equal to the number of rows of first matrix
* number of columns equal to the number of columns of the second matrix

Matrix-to-Matrix multiplication is not element to element operation like addition and subtraction seen above. An element in the product is derived by the sum of products of elements in rows of first matrix and columns of second matrix. It is for this reason that length of each row in first matrix (i.e. number of columns in first matrix) should be equal to the length of each column in second matrix (i.e. number of rows in second matrix).

Scalar-Matrix Multiplication:
<br>
<img src="../../../images/matscal_mul.PNG" style="width:70vw">
<br>

Matrix-to-Matrix Multiplication
<br>
<img src="../../../images/matmul_2.PNG" style="width:70vw">
<br>

This operation can be acheived by using either the 'dot' (dot product) function or the 'matmul' function in numpy module. These functions generally take two arguments, i.e., the two matrices which should be multiplied.

For example:
```python
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[2,1]])

print(np.matmul(a,b))

# Output
>>> [[ 5  4]
>>>  [11 10]]

```
<br>
<b>Note:</b> There is no such thing as <b>division operation</b> in matrices. However, a special operation called inverse of a matrix exists which we would learn about in the next notebook.

#### Exercise

Perform addition, subtraction and multiplication operations on the given matrices. Store the result in 3 variables - addition, subtraction and multiplication and print them out.

In [19]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])

addition = a+b
subtraction = a-b
multiplication = np.matmul(a,b)

print(addition,"\n",subtraction,"\n",multiplication)

[[2 3]
 [4 5]] 
 [[0 1]
 [2 3]] 
 [[3 3]
 [7 7]]


# More Matrix Operations and Special Matrices

## Transpose, Determinant and Inverse of a Matrix¶

### Transpose Operation

In [ ]:
Transpose Operation
A transpose operation on a matrix converts each row of entries into a column and in effect, the rows of original matrix 
become columns in the transposed matrix and columns of the original matrix become rows in the transposed matrix. i.e., 
If the dimensions or shape of the matrix is  (i,j)  then the transpose of this matrix will have a shape of  (j,i) .

numpy.transpose() method can be used to find out the transpose of a matrix.


In [20]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
''' Note: An interesting point to observe is that the transpose operation does not affect the position of the entries on 
the primary or leading diagonal of a square matrix.

What about the anti-diagonal (trailing diagonal) entries of the square matrix? They are reversed in order, i.e., the top most 
entry becomes the bottom most entry and the bottom most entry becomes the top most.'''

In [21]:
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.transpose(A))

[[ 8 43 11]
 [15  2 25]
 [30  9 62]]


In [ ]:
## Determinant of a Matrix
The determinant of a matrix is a scalar value which holds a significant value in linear operations that can be performed on 
the matrix. It is a value that can be calculated only for square matrices.
For a matrix  A , it is represented as det(A) or | A |.

The determinant is calculated by a series of arithematic operations. The following figure shows calculation of determinant 
for various matrices.

For a 2x2 matrix:
    For a 4x4 matrix:
Follow the same steps as defined above.

Exclude row and column that ‘a’ belongs to and calculate determinant for remaining portion of the matrix
Add the calculated part to the expression on the right hand side of the equation
Repeat steps 1 and 2 for all remaining elements in first row
After adding all terms to the right hand side, add alternating ‘–’ and ‘+’ operations to complete the calculation
For matrices of higher dimensions, determinants are calculated by help of a calculator.

In python, determinant of any matrix (or multi-dimensional array) can be calculated using the 'det' function in 
the 'linalg' sub-module of the numpy package.

In [22]:
import numpy as np

a = np.array([[1,2],[3,4]])

print(np.linalg.det(a))

-2.0000000000000004


In [23]:
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.linalg.det(A))

-7722.999999999992


## Inverse of a Matrix
For scalar values, we have the concept of 'reciprocal'. If a number is multiplied by its reciprocal the result is '1'. Similarly, there is a matrix called 'Identity matrix' (which we have studied in last notebook) among matrices.

The Inverse of a matrix is similar to 'reciprocal' of a matrix, i.e., when you multiply a matrix and its inverse, 
the resulting product would be an Identity matrix.

Say, if  𝐴  is a square matrix of order n x n, and  𝐼  is a identity matrix of order n x n, then

𝐴  *  𝐴−1  =  𝐼 

### Note that Inverse concept among matrices is applicable only in the case of square matrices.

Calculating inverse of a 2x2 matrix is easy, however, inverse calculation for 3x3 or higher dimensions is very complex. See below example for calculation of inverse for a 2x2 matrix.



The Inverse of a matrix can be determined by using the 'inv' function of 'linalg' sub-module of numpy ( 𝑛𝑢𝑚𝑝𝑦.𝑙𝑖𝑛𝑎𝑙𝑔.𝑖𝑛𝑣() ). This function can be performed on a numpy array (matrix).

In [24]:
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.linalg.inv(A))

[[ 0.01307782  0.02330701 -0.00971125]
 [ 0.33238379 -0.02149424 -0.15771073]
 [-0.13634598  0.00453192  0.08144503]]


## Comparing two matrices
The 'equal to' operator, if used to compare the equality of two matrices, first checks whether the dimensions of both matrices are same or not. If they are, then the operator compares each entry of first matrix with corresponding entry in second matrix and returns a boolean matrix of the same dimensions as compared matrices. If we are expecting a single boolean answer for equality of two matrices, the best way to do that is by using the 'allclose' or 'array_equal' functions.

### allclose and array_equal functions: 
numpy.array_equal() method can be used to test whether two arrays are equal to each other in terms of shape and elements. numpy.allclose() function performs the same operation but it has tolerance while matching elements, which enables it to compare floating point elements with varying accuracies/decimals.

For example:

In [25]:
A = np.array([[8,15,30],[43,2,9],[11,25,62]])
B = np.array([[8,15,30],[43,2,9],[11,25,62]])

print(np.allclose(A,B))

True


### Exercise
Calculate the inverse of the below given matrix. Create an Identity matrix of dimensions equal to the below given square 
matrix and use the allclose() function to verify whether the product of the below given matrix and its inverse yeilds 
the identity matrix.

In [26]:
import numpy as np

A = np.array([[8,15,30],[43,2,9],[11,25,62]])
A_inv = np.linalg.inv(A)

I = np.eye(3)

print(np.allclose(np.matmul(A,A_inv),I))

True


## Special Matrices

### Symmetric Matrix¶
A matrix which is equal to its transpose is called a symmetric matrix. If  𝐴  is a matrix, then  𝐴  is a symmetric matrix if:

𝐴𝑇=𝐴

### Exercise
Use the transpose function to calculate transposes of above given matrices -  𝐴  and  𝐵 . Use the allclose() function to verify if they are equal to their 
respective transpose matrix and verify if  𝐴  and  𝐵  are symmetric matrices.

In [27]:
import numpy as np

A = np.array([[1,2,3],[2,2,2],[3,2,3]])
B = np.array([[3,7,8],[7,1,4],[8,4,8]])

A_trans = np.transpose(A)
B_trans = np.transpose(B)

print(np.allclose(A,A_trans), np.allclose(B,B_trans))

True True


## Skew-Symmetric Matrix
A matrix is said to be skew-symmetric if its transpose is equal to the negation of the original matrix. i.e., If  𝐴  is a matrix, then  𝐴  is a skew-symmetric matrix if:

𝐴𝑇=−𝐴 
An example of symmetric matrix is

𝐴=0−2−320−2320 
Another example:

𝐵=0−7−870−4840 
Note: The entries in the primary diagonal of a skew-symmetric matrix are always zeros and the entries on the upper side of the primary diagonal are all positive while the entries on the lower side of the primary diagonal are all negative.

### Exercise
Use the transpose function to calculate transposes of above given matrices -  𝐴  and  𝐵 . Use the allclose() function to verify if the transposes of the matrices are equal to a negated version of their original matrix and verify if  𝐴  and  𝐵  are skew-symmetric matrices.

In [28]:
import numpy as np

A = np.array([[0,2,3],[-2,0,2],[-3,-2,0]])
B = np.array([[0,7,8],[-7,0,4],[-8,-4,0]])

A_trans = np.transpose(A)
B_trans = np.transpose(B)

print(np.allclose(-A,A_trans), np.allclose(-B,B_trans))

True True


### Singular Matrix
A singular matrix is one for which no inverse exists. This is possible when the determinant of the matrix is zero. Let us say  𝐴  is a matrix,  𝐴  is said to be singular if

det( 𝐴 )=0

thereby,

𝐴−1  = undeterminable

An example of singular matrix is:

𝐴=[2222] 
another example:

𝐵=[51048] 
A 3x3 singular matrix:

𝐶=0−2−4200324 
### Exercise
Try to calculate determinants of above given matrices  𝐴,𝐵,𝑎𝑛𝑑𝐶  and verify if they are truly singular matrices or not.

Also, try calculating the inverse of any of these matrices and observe the output.

In [29]:
import numpy as np

A = np.array([[2,2],[2,2]])
B = np.array([[5,4],[10,8]])
C = np.array([[0,2,3],[-2,0,2],[-4,0,4]])

print(np.linalg.det(A),np.linalg.det(B),np.linalg.det(C))
print(np.linalg.inv(A))

0.0 0.0 0.0


LinAlgError: Singular matrix

In [35]:
import numpy as np 

A = np.array([
    [1,1,2],
    [3,5,8]
])

B = np.array([
    [2,3,5],
    [7,11,13]
])

c = np.array([
    [3,1,4],
    [1,5,9],
    [2,6,5],
    [3,5,6]
])

print (A + B)
print(A-B)
print (100*C)

[[ 3  4  7]
 [10 16 21]]
[[-1 -2 -3]
 [-4 -6 -5]]
[[   0  200  300]
 [-200    0  200]
 [-400    0  400]]


In [36]:
import numpy as np 
from scipy.spatial import distance

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
 
import numpy as np

import random

from IPython.display import display, Math

from bokeh.io import show, output_notebook, reset_output
from bokeh.plotting import figure, show
from scipy.stats import norm 
from bokeh import plotting as pl
from bokeh.models import HoverTool, Arrow, OpenHead, NormalHead, VeeHead, Span, ColumnDataSource, PointDrawTool, TableColumn,  DataTable


output_notebook()


Loading BokehJS ...

# Eigenvalues and eigenvectors
In this notebook we are going to be talking about one of the most important concepts in linear algebra related to machine learning.

Understanding Eigenvalues and eigenvectors form is important to understand some of the most commonly used tools for machine learning like- singular value decomposition (SVD), principal component analysis (PCA) etc.

We are not going to go into great mathematical details eigenvalues and eigenvectors. For the most part we will use python functions to do the eigenvalues and eigenvector calculations.

So parts we are going to cover in this notebook are -

The problem setup     
Calculating eigenvalues     
Calculating eigenvectors     

## The problem setup      
The concept of eigenvectors and eigenvalues come in when we talk about solving the equation of the form-    

𝐴𝐱=𝜆𝐱
 
where-

𝐴  is a square matrix, for now we are going to stick with a 2 by 2 matrix
𝐱  is some unknown vector  𝜆  is a constant that will later on represent the eigenvalues

It is prudent to point out that  𝐴  has to be a square matrix. Meaning either a  2×2  matrix or a  3×3  matrix or an  𝑛×𝑛  matrix where n = 2,3,4,5... etc. Basically  𝑛  can be any positive integer.

Now why do we care about this specific form? Well for that let us decode the equation above. On the right hand side, what we are in essence doing is applying a linear transformation to the unknown vector  𝐱 . For example let us apply the transformation

𝐴=[10
   01] 
to some vector. In the plot below we show the result-

In [37]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


fig = pl.figure(x_range =[-10,10],
                    y_range =[-10,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis", 
                   title  = "Original vs transformed vector "
                   )

vec_x =2
vec_y =5

vec_1 = np.array([vec_x,vec_y])
trans_matrix =  np.matrix([[1,0],[0,-1]])
trans_vec = np.array(trans_matrix.dot(vec_1))

transformation  = 1
vline = Span(location=0, dimension='height', line_color='black', line_width=2)
hline = Span(location=0, dimension='width', line_color='black', line_width=2)

fig.renderers.extend([vline, hline])
fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=2,
                       y_end=5 
                    ))

fig.text(x=vec_x, y =vec_y, text =["original \n vector"])
fig.text(x=trans_vec[0][0], y =(trans_vec[0][1])-3.0, text =["transformed \n vector " ])

fig.add_layout(Arrow(end=NormalHead(fill_color="green", line_color = "green" ),
                       x_start=0,
                       y_start=0,
                       x_end=trans_vec[0][0],
                       y_end=trans_vec[0][1] 
                    ))


show(fig)


The original vector is transformed due to the transformed to the green vector. We can apply different types of transformations to vector  𝐱 . Now what we are saying with equation (1) is that can we find a vector which is going to point in the same direction as the original vector but it scales by a value  𝜆  In order to find such a vector we are going to solve the linear system-

(𝐴−𝜆𝐼)𝐱=0
 
where-  𝐼  is the identity matrix

The solution to this will come in the form of us getting values of of  𝜆  which will be the eigenvalues.

## Calculating eigenvalues
Now for equation (2) to be true you need one of two things to be true either  𝐱=0  or  (𝐴−𝜆𝐼)=0 . Since the first condition will not be true (we are effectively making this choice). The second condition must be true. Hence we will have the condition that-

det(𝐴−𝜆𝐼)=0
 
where we have
det(𝐴−𝜆𝐼)=det([𝑎11−𝜆𝑎21𝑎12𝑎22−𝜆])=0
 
we can do some simple algebra and get

det(𝐴−𝜆𝐼)=𝜆2−𝜆(𝑎11+𝑎22)+𝑎11𝑎22−𝑎12𝑎21=0
 
Well there are only two solutions to this equation. They are-
𝜆1=12[(𝑎11+𝑎22)+(4𝑎12𝑎21+(𝑎11−𝑎22)2)⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯√]𝜆2=12[(𝑎11+𝑎22)−(4𝑎12𝑎21+(𝑎11−𝑎22)2)⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯√]
So now we have our eigenvalues for a  2×2  matrix. We can use this procedure to calculate the eigenvalues "by hand" for larger matrices but if you try it you will find that finding solutions for more that a  3×3  matrix will quickly become rather challenging. Thankfully python gives us a quick way of calculating eigenvalues for a given matrix. Below is some code on how to get eigenvalues for a  2×2  and a  4×4  -

In [38]:
# 2 by 2 matrix 
test_mat_2 = np.array([[2,1],[3,2]])
print(" eigenvalues of the 2 by 2 matrix {}".format(np.linalg.eigvals(test_mat_2)))


# 4 by 4 matrix 
test_mat_4 = np.array([[8,5,2,3],[4,9, 6, 3], [4,7, 3, 1],[2,1,5,6]])
print(" eigenvalues of the 4 by 4 matrix {}".format(np.linalg.eigvals(test_mat_4)))

 eigenvalues of the 2 by 2 matrix [3.73205081 0.26794919]
 eigenvalues of the 4 by 4 matrix [18.00284658 -0.09828708  4.79597699  3.29946351]


## Calculating eigenvectors¶
Now that we the eigenvalues we can get the eigenvectors. The full scope of how we get the eigen vectors is beyond the scope of this notebook, we will show you how you can get those eigenvectors from python directly. So, if we take the  2×2  and the  4×4  matrix from above, the eigenvectors would be-

In [39]:
# 2 by 2 matrix 
test_mat_2 = np.array([[2,1],[3,2]])
eigenvectors = np.linalg.eig(test_mat_2)[1::]
print("the eigen vectors for the 2 by 2 matrix are{}" .format(eigenvectors)) 


# 4 by 4 matrix 
test_mat_4 = np.array([[8,5,2,3],[4,9, 6, 3], [4,7, 3, 1],[2,1,5,6]])
print(" eigenvalues of the 4 by 4 matrix {}".format(np.linalg.eig(test_mat_4)[1::]  ))

the eigen vectors for the 2 by 2 matrix are(array([[ 0.5      , -0.5      ],
       [ 0.8660254,  0.8660254]]),)
 eigenvalues of the 4 by 4 matrix (array([[-0.5133916 , -0.27966899,  0.76085192, -0.655923  ],
       [-0.64471836,  0.37315332, -0.53758366,  0.26987163],
       [-0.45973711, -0.66886331, -0.25838121, -0.16213823],
       [-0.33077046,  0.57893326,  0.25563121,  0.68603609]]),)


So you can see that for a  2×2  matrix we are going to have a two eigenvectors. Each eigenvector will be 2 units long. For the  4×4  vector we have four eigenvectors and four eigenvalues.